import React from 'react'
import { Container, Row, Col } from 'react-bootstrap';

const About = () => {
  return (
    <>
        <Container style={{marginTop: '50px'}}>
            <h1>Qui sommes-nous ?</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi deserunt minus reprehenderit dolore laborum eos perferendis voluptatibus perspiciatis enim excepturi rerum fugiat dolor, amet ex odit saepe, id consequuntur natus harum eum ratione magni molestiae magnam porro. Expedita corporis, laudantium voluptatem sapiente itaque eveniet veritatis atque ea ut laboriosam ipsam harum. Laboriosam praesentium ipsam voluptate maxime dolor? Optio minima non harum rerum, cupiditate fuga voluptatem dolores excepturi, sapiente, dolore esse in laborum odio ullam commodi nostrum accusamus quo molestias quas. Enim veritatis maxime quo illum ducimus nostrum reiciendis deserunt. Ipsa quod sint exercitationem officia laborum consequuntur ad modi pariatur ab distinctio ipsum aliquid amet quam nemo recusandae doloremque aliquam dolore, non architecto repellendus repudiandae quia! Velit delectus fuga cum quisquam libero doloribus voluptas quae, doloremque sit dolorem eius recusandae obcaecati praesentium maxime quas neque numquam! Quas quasi deserunt sint distinctio quaerat illum vel, consequatur eum recusandae repudiandae ipsam at aliquam voluptate cum atque debitis ratione nesciunt, modi et amet? Rerum dolorem magnam quae a molestias ullam ipsum, adipisci dignissimos veniam velit error asperiores facere. Eveniet officia fugiat et assumenda, optio, provident debitis fugit architecto impedit corrupti illo magni consequatur error sapiente qui similique voluptatem suscipit, doloremque nesciunt quisquam. Corrupti, dolorem!</p>
            <h1>Notre spécialité</h1>
            <Row>
                <Col md={6}>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti facere eaque est deserunt alias doloremque distinctio, harum modi adipisci optio sit voluptate, possimus voluptates commodi nemo. Quas, illum consequuntur amet accusamus illo deleniti a blanditiis vero adipisci id beatae aperiam eum cumque consequatur ullam asperiores assumenda voluptate dolore? Dolorem sit laudantium error explicabo ipsa. Minima cupiditate molestias inventore unde repudiandae recusandae repellendus perspiciatis, sint quis odio adipisci rerum explicabo maxime maiores quaerat laborum ex? Sint neque magni impedit molestias dolores ipsa voluptas sit error illum maxime sunt officiis molestiae fugit, natus minus fugiat in doloribus modi. Quis, ex eaque laboriosam, corporis neque officiis dolores odio consequuntur vero expedita totam id non tenetur! Earum repudiandae voluptas nulla, magni quia fugiat et enim adipisci iure labore possimus, sequi aliquam eius. Voluptatibus laudantium quae magni quasi nihil similique dolores reprehenderit excepturi dignissimos debitis, est fugit voluptate quod iusto veritatis? Consequatur autem quibusdam alias tempora. Sunt similique quae qui sequi tenetur aliquam. Eos quas veniam enim ad sed blanditiis nihil harum, et sint aspernatur, numquam voluptatem saepe minima labore! Quia, vitae iure facilis velit aliquam quidem rem ab fugiat dolorem quae doloremque, laborum unde cumque eius ut odio, aliquid commodi autem porro dolores. Sequi.</p>
                </Col>
                <Col md={6}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga sequi placeat doloribus quam ea, rem ex aut sed atque sint, illum rerum ducimus! Praesentium expedita pariatur laudantium? Perferendis voluptatibus nobis iure doloremque beatae adipisci ab velit unde veniam repellendus totam, dignissimos rem laudantium libero a excepturi architecto, consequuntur in. Sapiente voluptas architecto doloremque nam iste id suscipit eum tempore animi tempora pariatur maiores fuga voluptatibus ab dolore consequatur eos soluta eius aperiam, ratione, amet neque. Amet facere vel consequuntur impedit reiciendis ipsum similique porro molestias qui vitae veniam totam cumque incidunt mollitia laboriosam repellendus cupiditate, corrupti ratione tenetur obcaecati autem velit vero culpa ex. Maxime a debitis natus nihil eligendi fuga quibusdam tempora adipisci! Ex fugit a nam non quae. Placeat illum vero alias. Delectus necessitatibus dolorem laborum eaque minus debitis sit, culpa vel sapiente mollitia enim dolor perferendis consequatur, assumenda iure omnis. Dignissimos beatae repellat totam ipsam aliquam quia adipisci facilis nostrum rem, modi, ea mollitia commodi earum pariatur provident corrupti? Odio ratione quos, odit porro autem ipsam eveniet sed veritatis consequuntur vel. Omnis ad iure voluptatum velit fugiat excepturi non perspiciatis ex tempore modi amet qui consequatur ipsam, esse reiciendis eveniet repellat dolore hic natus eos harum officia.</p>
                </Col>
            </Row>
            <Row>
                <h1>Le Chef</h1>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum ex praesentium inventore, consequuntur aliquam quidem voluptatum nulla blanditiis, nostrum suscipit reiciendis autem provident repellat, minima repellendus quae fuga. Repellat facilis ullam saepe porro laborum placeat iusto dolor amet doloribus nulla? Similique eos quia culpa iure, unde ad dicta, id omnis officia minus veritatis, odio quidem architecto numquam ullam suscipit quas impedit hic. Cumque sint consequuntur reprehenderit, repudiandae voluptas, aspernatur in nisi, dignissimos ad dicta esse sapiente recusandae sed. Quasi quaerat nesciunt dolores molestiae. Corporis, obcaecati? Quibusdam nostrum blanditiis ab quo ducimus ipsam, rem, amet dolore itaque tempora ratione perspiciatis consequatur.</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi mollitia, totam harum modi in distinctio doloremque cupiditate pariatur, eum aliquam qui cumque inventore iusto, sunt assumenda obcaecati quis? Cupiditate, harum similique veniam nesciunt vel perspiciatis rem consectetur voluptatibus ratione itaque fuga adipisci fugit fugiat saepe atque? Voluptatem sequi, quasi recusandae hic quae minus necessitatibus maiores ex explicabo expedita, a, modi atque! Repellendus assumenda sint possimus dolorem, libero asperiores nesciunt voluptate repudiandae, aut odio impedit adipisci dolore, tempora aspernatur atque alias. Pariatur facilis non aspernatur. At, perspiciatis rerum corrupti itaque, maxime est reiciendis eius minus, sapiente harum ipsa magni qui ab.</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure cupiditate saepe provident facere, culpa voluptatem consequuntur corporis debitis ipsam eveniet ut, aliquid dolore beatae dignissimos fugiat recusandae omnis iusto nihil atque sapiente natus quibusdam deleniti illo. Assumenda minus consectetur rem, labore obcaecati suscipit officiis. Eum nulla dicta ea a commodi accusantium autem asperiores, ipsam id ex tenetur, quos quo provident iure quis cumque. Reprehenderit voluptates, odit recusandae et accusantium at. Ad nesciunt sapiente enim voluptatem debitis alias, officia iste nobis nihil nam libero neque distinctio cumque iusto veritatis, eveniet modi hic dicta? Eligendi eos et quas asperiores veritatis! Impedit, repellendus?</p>
                </Col>
                <Col md={3}>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione dolorem rerum similique minus totam, non nostrum est molestias omnis voluptates quas nihil laudantium pariatur, molestiae voluptatibus doloribus dolorum! Sapiente explicabo accusamus recusandae itaque molestiae harum doloribus, officia consequuntur voluptatum iure, obcaecati quidem velit tenetur assumenda quos nulla fuga voluptatibus porro aliquam. Eveniet excepturi et a, expedita suscipit aspernatur itaque assumenda harum maiores maxime ipsam, nobis tempore, repudiandae necessitatibus quisquam quasi autem provident aperiam quia quibusdam molestias ratione. Sunt eligendi, assumenda, molestiae eos repudiandae voluptas nisi, laudantium ipsam id est voluptate quae quas praesentium modi iusto aliquam earum! Veritatis, aut obcaecati!</p>
                </Col>
            </Row>
        </Container>
    </>
  )
}

export default About;